### ISSUE TITLE
Camera is permanently active once used for a capture until the application is closed

### ISSUE THREAD

**Issue by dgervalle** [alienator88/Viz#22]
Once you use the camera capture feature, the camera stay active (green led on) by Viz until Viz is closed.

Expectation would be that closing the capture window, the camera is no more used.

**Comment by alienator88** [comment]
Ah good catch, let me look at it.

**Comment by alienator88** [comment]
I pulled the new version temporarily, I'll submit it again with a fix for the camera staying on.

**Comment by alienator88** [comment]
Fixed. Pushing out the same version again with both fixes.
You'll need to redownload manually since you're already on that newer version.

**Comment by dgervalle** [comment]
Well, IMO, almost closed, but still happen when you close the capture window too fast !
I don't have right to reopen this issue however :(

**Comment by alienator88** [comment]
Can you list reproduction steps I can take directly?
I didn't see anything on my end.

**Comment by dgervalle** [comment]
Just be too fast closing the capture window once the video is shown after opening it by clicking on the webcam button in the menu.
If you are fast enough, closing does not terminate the camera capture, the green led stays on. When slightly slower, all goes as expected.

**Comment by alienator88** [comment]
That's what I've been trying, I open the capture view and close it as fast as I can move the mouse to it.
It shuts off the LED every time on my end..hmm..
What is slightly slower in this scenario? Like what is the shortest amount you can wait between opening the capture window and closing it to where the LED still shuts off? Like a second, 2 seconds?

**Comment by dgervalle** [comment]
I don't really know what to say. On my end, when the camera window appear, it takes about 2 seconds for the camera to start, than the video starts to fade in, and if I close at that moment, as soon as I see the video, it's staying on, but if I wait until the light adjustment is done, it's ok.

**Comment by alienator88** [comment]
What kind of computer are you running on? Specs?

The reason is likely that the window hasn't fully finished rendering. I added a notification observer that listens for when the window is closed to disable the camera. If the window is closed before the notification observer is setup, it has no way of knowing that it was closed.

**Comment by dgervalle** [comment]
I am on a MacBook Pro M3 Max released 2 years ago (Mac15,9), the windows open instantly, but it's initially black with the starting camera icon, if I close it before the camera is fully initialized, including the light adjustment fully done, which takes between 2 and 3 seconds, you miss the catch apparently.

**Comment by alienator88** [comment]
Are you testing with the built-in camera?
One thing I didn't take into account is I have an external webcam.

**Comment by dgervalle** [comment]
Yes, I do

**Comment by alienator88** [comment]
Can you try the new release? Had to push it out before you tested because homebrew bumped my cask to 2.3.2 right as I removed it so now people can't install it. I pushed 2.3.3, with hopefully a fix for you too.

I still couldn't reproduce the problem on my end. Not sure why, my camera loads in really fast on external and built-in.

**Comment by dgervalle** [comment]
That's even more puzzling with 2.3.3, now if I am very fast so the camera led is green but the screen is still black or slow enough for the camera to be fully setup, it works, but in between, when  I close while the camera is tuning the brightness, it fails.

**Comment by alienator88** [comment]
Definitely puzzling. I'm out of ideas here, it's just very hard to fix a bug when I can't see it and test on it :(

**Comment by dgervalle** [comment]
I completely understand your situation, and I am sorry if I have not provided enough information. My expertise in Swift development is quite limited. I’ve included the log file ([viz.log](https://github.com/user-attachments/files/23221746/viz.log)) that I captured during a failed session stop (up to 23:54:30), followed by a successful one. I hope this helps spark some ideas for you, but I fear that some errors may be concealed. I hope it could give you more ideas. I would definitely understand if you want to give up. Please let me know if I can do more to help.

**Comment by alienator88** [comment]
I will mess around with it more when I have some time. 
That log helps though, I'll poke around and see what I find.
I'll likely need you to test a few more builds since I can't test the fixes 😂

**Comment by dgervalle** [comment]
Sure, you're welcome with any new build to be tested, and I fully understand the challenge. Let me know if need anything else that could help.
